// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: spring/options/service.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpringOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFlux        bool                   `protobuf:"varint,1,opt,name=is_flux,json=isFlux,proto3" json:"is_flux,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpringOption) Reset() {
	*x = SpringOption{}
	mi := &file_spring_options_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpringOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpringOption) ProtoMessage() {}

func (x *SpringOption) ProtoReflect() protoreflect.Message {
	mi := &file_spring_options_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpringOption.ProtoReflect.Descriptor instead.
func (*SpringOption) Descriptor() ([]byte, []int) {
	return file_spring_options_service_proto_rawDescGZIP(), []int{0}
}

func (x *SpringOption) GetIsFlux() bool {
	if x != nil {
		return x.IsFlux
	}
	return false
}

var file_spring_options_service_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*SpringOption)(nil),
		Field:         60000,
		Name:          "spring.options.spring_option",
		Tag:           "bytes,60000,opt,name=spring_option",
		Filename:      "spring/options/service.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional spring.options.SpringOption spring_option = 60000;
	E_SpringOption = &file_spring_options_service_proto_extTypes[0]
)

var File_spring_options_service_proto protoreflect.FileDescriptor

const file_spring_options_service_proto_rawDesc = "" +
	"\n" +
	"\x1cspring/options/service.proto\x12\x0espring.options\x1a google/protobuf/descriptor.proto\"'\n" +
	"\fSpringOption\x12\x17\n" +
	"\ais_flux\x18\x01 \x01(\bR\x06isFlux:g\n" +
	"\rspring_option\x12\x1f.google.protobuf.ServiceOptions\x18\xe0\xd4\x03 \x01(\v2\x1c.spring.options.SpringOptionR\fspringOption\x88\x01\x01B\x86\x01\n" +
	"\x12com.spring.optionsB\fServiceProtoP\x01Z\t.;options\xa2\x02\x03SOX\xaa\x02\x0eSpring.Options\xca\x02\x0eSpring\\Options\xe2\x02\x1aSpring\\Options\\GPBMetadata\xea\x02\x0fSpring::Optionsb\x06proto3"

var (
	file_spring_options_service_proto_rawDescOnce sync.Once
	file_spring_options_service_proto_rawDescData []byte
)

func file_spring_options_service_proto_rawDescGZIP() []byte {
	file_spring_options_service_proto_rawDescOnce.Do(func() {
		file_spring_options_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spring_options_service_proto_rawDesc), len(file_spring_options_service_proto_rawDesc)))
	})
	return file_spring_options_service_proto_rawDescData
}

var file_spring_options_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_spring_options_service_proto_goTypes = []any{
	(*SpringOption)(nil),                // 0: spring.options.SpringOption
	(*descriptorpb.ServiceOptions)(nil), // 1: google.protobuf.ServiceOptions
}
var file_spring_options_service_proto_depIdxs = []int32{
	1, // 0: spring.options.spring_option:extendee -> google.protobuf.ServiceOptions
	0, // 1: spring.options.spring_option:type_name -> spring.options.SpringOption
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spring_options_service_proto_init() }
func file_spring_options_service_proto_init() {
	if File_spring_options_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spring_options_service_proto_rawDesc), len(file_spring_options_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_spring_options_service_proto_goTypes,
		DependencyIndexes: file_spring_options_service_proto_depIdxs,
		MessageInfos:      file_spring_options_service_proto_msgTypes,
		ExtensionInfos:    file_spring_options_service_proto_extTypes,
	}.Build()
	File_spring_options_service_proto = out.File
	file_spring_options_service_proto_goTypes = nil
	file_spring_options_service_proto_depIdxs = nil
}
